image:
  registry: docker.io
  repository: ~
  tag: latest
  pullPolicy: Always

serviceType: LoadBalancer

createDB: false

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 1000m

db:
  persistence:
    enabled: true
